  
version: '3'
services:
  test-search:
    build:
      context: ./my-app
      dockerfile: Dockerfile-dev
    ports:
      - "8090:8080"
    container_name: test-search
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules